[package]
name = "bubshurb/propertyutil"
description = "A utility module for working with the [Property](https://babypatrick100.github.io/libraries/api/Property/) class."
authors = ["bubshurb"]
version = "1.0.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Property = "bubshurb/property@2"