[package]
name = "bubshayz/numberunitutil"
description = "An utility module for working with number units."
authors = ["bubshayz"]
license = "MIT"
version = "1.2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Loader = "sleitnick/loader@2"