[package]
name = "bubshurb/seatutil"
description = "A utility module for working with seats."
authors = ["bubshurb"]
version = "1.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Property = "bubshurb/property@2"
Sift = "csqrl/sift@0"
Trove = "sleitnick/trove@1"
playersUtil = "bubshurb/playersutil@1"