[package]
name = "bubshurb/soundutil"
description = "A utility module for working with sounds."
authors = ["bubshurb"]
version = "1.2.2"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@2"
Trove = "sleitnick/trove@1"