
[package]
name = "bubshurb/playercharacteraccessoryutil"
description = "A simple utility module for working with the player's character's accessories."
authors = ["bubshurb"]
license = "MIT"
version = "2.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"