[package]
name = "bubshayz/instanceutil"
description = "An utility module for working with instances."
authors = ["bubshayz"]
license = "MIT"
version = "1.9.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"