[package]
name = "bubshurb/zoneplus"
description = "ZonePlus by 1ForeverHD, ported to wally."
version = "2.0.0"
authors = ["1ForeverHD"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"