[package]
name = "bubshurb/badgeserviceutil"
description = "An utility module for working with [BadgeService](https://create.roblox.com/docs/reference/engine/classes/BadgeService)."
authors = ["bubshurb"]
license = "MIT"
version = "1.2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4"