[package]
name = "bubshayz/schedulerutil"
description = "	A simple utility module for scheduling RunService events with minimal performance impacts and with automatic profiling."
authors = ["bubshayz"]
version = "1.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
debugLoggerUtil = "bubshayz/debugloggerutil@1"