[package]
name = "bubshurb/viewportframeutil"
description = "A simple utility for working with [ViewportFrame](https://create.roblox.com/docs/reference/engine/classes/ViewportFrame)."
authors = ["bubshurb"]
version = "1.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Trove = "sleitnick/trove@1"
ViewportModel = "bubshurb/viewportmodel@1"
schedulerUtil = "bubshurb/schedulerutil@1"