[package]
name = "bubshurb/windlines"
description = "A module for creating wind line effects."
authors = ["bubshurb", "boatbomber"]
version = "1.0.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@2"
Janitor = "howmanysmall/janitor@1"
t = "osyrisrblx/t@3"