[package]
name = "bubshurb/beamutil"
description = "A simple utility for working with beams."
authors = ["bubshurb"]
version = "1.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"