[package]
name = "bubshurb/matrixutil"
description = "An utility module for working with matrixes."
authors = ["bubshurb"]
license = "MIT"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"