[package]
name = "bubshurb/marketplaceserviceutil"
description = "An utility module for working with [MarketplaceService](https://create.roblox.com/docs/reference/engine/classes/MarketplaceService)."
authors = ["bubshurb"]
version = "1.2.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4"