[package]
name = "bubshurb/playersutil"
description = "A simple utility module for working with the [Players](https://create.roblox.com/docs/reference/engine/classes/Players) service."
authors = ["bubshurb"]
version = "1.4.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4"