[package]
name = "bub/playersutil"
description = "A simple utility module for working with the Players service."
authors = ["bub"]
version = "1.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4"