[package]
name = "bubshurb/textserviceutil"
description = "Wrapper for [TextService](https://create.roblox.com/docs/reference/engine/classes/TextService)."
authors = ["bubshurb"]
version = "1.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4"