[package]
name = "bubshurb/instancetroveutil"
description = "An utility module for working with instance troves."
authors = ["bubshurb"]
license = "MIT"
version = "2.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Trove = "sleitnick/trove@1"