[package]
name = "bubshurb/colorsequenceutil"
description = "A simple utility module for working with color sequences."
authors = ["bubshurb"]
version = "1.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"