[package]
name = "bubshayz/instancereplicationutil"
description = "An utility module for working with instance replication."
authors = ["bubshayz"]
license = "MIT"
version = "1.3.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4"