[package]
name = "bubshurb/timer"
description = "The Timer class allows for code to run periodically at specified intervals."
authors = ["bubshurb"]
version = "1.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@2"
Trove = "sleitnick/trove@1"
schedulerUtil = "bubshurb/schedulerutil@1"