[package]
name = "bubshurb/numberformatutil"
description = "A simple utility for working with numbers and strings."
authors = ["bubshurb"]
license = "MIT"
version = "2.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"