[package]
name = "bubshayz/numberutil"
description = "An utility module for working with numbers."
authors = ["bubshayz"]
license = "MIT"
version = "2.3.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Loader = "sleitnick/loader@2"