[package]
name = "bubshayz/waitforutil"
description = "An utility module for [WaitFor](https://sleitnick.github.io/RbxUtil/api/WaitFor/)."
authors = ["bubshayz"]
version = "1.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Loader = "sleitnick/loader@2"