[package]
name = "bubshurb/positionutil"
description = "An utility module for working with position."
authors = ["bubshurb"]
license = "MIT"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"