[package]
name = "bubshurb/queryutil"
description = "A utility for basic query operations."
authors = ["bubshurb"]
version = "1.3.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Trove = "sleitnick/trove@1"
Property = "bubshurb/property@2"