[package]
name = "bubshurb/connection"
description = "A simple class for mimicking [RBXConnection](https://create.roblox.com/docs/reference/engine/datatypes/RBXScriptConnection) objects."
authors = ["bubshurb"]
license = "MIT"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"