[package]
name = "bubshurb/clientmouseutil"
description = "A simple utility module for working with the client's mouse."
version = "1.1.0"
license = "MIT"
authors = ["bubshurb"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Connection = "bubshurb/connection@1"
schedulerUtil = "bubshurb/schedulerutil@1"