[package]
name = "bubshurb/lightingutil"
description = "A simple utility for working with [Lighting](https://create.roblox.com/docs/reference/engine/classes/Lighting)."
authors = ["bubshurb"]
license = "MIT"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"