[package]
name = "bubshayz/toolutil"
description = "A simple utility module for working with tools.."
authors = ["bubshayz"]
version = "1.2.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
playerUtil = "bubshayz/playerutil@2"