[package]
name = "bub/toolutil"
description = "A simple utility module for working with tools.."
authors = ["bub"]
version = "1.2.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
playerUtil = "bub/playerutil@2"