[package]
name = "bubshurb/toolutil"
description = "A simple utility module for working with tools."
authors = ["bubshurb"]
version = "2.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Connection = "bubshurb/connection@2"
playersUtil = "bubshurb/playersutil@2"
playerEventsUtil = "bubshurb/playereventsutil@1"