[package]
name = "bubshurb/contentproviderqueue"
description = "A simple class for working with ContentProvider."
authors = ["bubshurb"]
license = "MIT"
version = "1.2.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4"
Signal = "sleitnick/signal@2"
Janitor = "howmanysmall/janitor@1"
throttleUtil = "bubshurb/throttleutil@1"