[package]
name = "bubshayz/contentproviderqueue"
description = "A simple class for working with ContentProvider."
authors = ["bubshayz"]
license = "MIT"
version = "1.7.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4"
Signal = "sleitnick/signal@1"
Janitor = "howmanysmall/janitor@1"
throttleUtil = "bubshayz/throttleutil@1"