[package]
name = "bubshurb/clientmovementinpututil"
description = "A simple utility module which wraps `PlayerModule` and `PlayerModule.ControlModule`."
authors = ["bubshurb"]
version = "1.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"