[package]
name = "bubshurb/hover"
description = "A simple hover class for implementing hover effects."
authors = ["bubshurb"]
license = "MIT"
version = "2.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"