[package]
name = "bubshayz/rbxscriptsignalutil"
description = "An utility module for working with RBXScriptSignals."
authors = ["bubshayz"]
license = "MIT"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"