[package]
name = "bubshurb/basepartresizeutil"
description = "A utility module for resizing base parts on specific axes."
version = "2.0.0"
license = "MIT"
authors = ["bubshurb"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4"
instanceTranslationUtil = "bubshurb/instancetranslationutil@1"