[package]
name = "bub/instancetrackerutil"
description = "A simple utility module for working with instances and their properties."
authors = ["bub"]
license = "MIT"
version = "7.3.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Property = "bub/property@3"