[package]
name = "bubshurb/instancenetworkownerutil"
description = "An utility module for working with instance network ownership."
authors = ["bubshurb"]
license = "MIT"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"