[package]
name = "bub/instancetagutil"
description = "A utility module for working with instance tags."
authors = ["bub"]
license = "MIT"
version = "1.4.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4"