[package]
name = "bubshurb/playerutil"
description = "An utility module for working with players."
authors = ["bubshurb"]
license = "MIT"
version = "1.4.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4"
Sift = "csqrl/sift@0"
playerPolicyInfoUtil = "bubshurb/playerpolicyinfoutil@1"