[package]
name = "bubshayz/playerutil"
description = "An utility module for working with players."
authors = ["bubshayz"]
license = "MIT"
version = "2.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4"
Sift = "csqrl/sift@0"
playerPolicyInfoUtil = "bubshayz/playerpolicyinfoutil@1"