[package]
name = "bubshurb/component"
description = "Component class by Sleitnick, heavily modified by babypatrick100."
version = "2.0.0"
license = "MIT"
authors = ["bubshurb"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@2"
Symbol = "sleitnick/symbol@2"
Trove = "sleitnick/trove@1"
Promise = "evaera/promise@4"