[package]
name = "bubshurb/colorutil"
description = "A simple utility module for working with colors."
authors = ["bubshurb"]
version = "2.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
colorSequenceUtil = "bubshurb/colorsequenceutil@1"