[package]
name = "bub/handlerhookerutil"
description = "A simple utility module for working with handlers."
authors = ["bub"]
license = "MIT"
version = "1.5.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4"