
[package]
name = "bubshurb/playerhumanoidutil"
description = "A simple utility module for working with the player's humanoid."
authors = ["bubshurb"]
license = "MIT"
version = "2.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4"
Signal = "sleitnick/signal@2"
Connection = "bubshurb/connection@2"
instancePropertyUtil = "bubshurb/instancepropertyutil@1"
playerEventsUtil = "bubshurb/playereventsutil@1"
instanceTroveUtil = "bubshurb/instancetroveutil@2"