[package]
name = "bub/customanimator"
description = "A simple class for working with animations."
authors = ["bub"]
license = "MIT"
version = "1.7.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4"
Signal = "sleitnick/signal@1"