[package]
name = "bubshurb/customanimator"
description = "A simple class for working with animations."
authors = ["bubshurb"]
license = "MIT"
version = "1.6.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4"
Signal = "sleitnick/signal@2"
instanceTroveUtil = "bubshurb/instancetroveutil@1"