[package]
name = "bubshayz/matterentityutil"
description = "Utility module for working with matter entities."
authors = ["bubshayz"]
license = "MIT"
version = "1.4.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4"