[package]
name = "bubshurb/basepartutil"
description = "An utility module for working with base parts."
authors = ["bubshurb"]
license = "MIT"
version = "2.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"