[package]
name = "bubshurb/serializerutil"
description = "A very simple utility for serializing and deserializing data types."
authors = ["bubshurb"]
version = "1.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Loader = "sleitnick/loader@2"