[package]
name = "bubshayz/serializerutil"
description = "A very simple utility for serializing and deserializing data types."
authors = ["bubshayz"]
version = "1.5.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Loader = "sleitnick/loader@2"