name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rokit
      uses: CompeyDev/setup-rokit@v0.1.2

    - name: Lint
      run: |
        selene src

  style:
    name: Styling
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Check code style
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ github.token }}
          version: latest
          args: --check src
        continue-on-error: true

      - name: Stylua Formatting
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ github.token }}
          version: latest
          args: src

      - name: Commit Stylua formatted files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[auto]: Format via Stylua"
          branch: ${{ github.head_ref }}