return table.freeze({
	Attribute = {
		NetworkFolder = "NetworkFolder",
		BoundToRemoteProperty = "BoundToRemoteProperty",
		BoundToRemoteSignal = "BoundToRemoteSignal",
		RemoteValueType = "RemoteValueType",
		AutomaticRemoteArgumentSerializationAndDeserializationEnabled = "AutomaticRemoteArgumentSerializationAndDeserializationEnabled",
		RemotePromisified = "RemotePromisified",
		RemotePropertyHadContainedInitialValue = "RemotePropertyHadContainedInitialValue",
	},
})
