[package]
name = "bub/network"
description = "An advanced network module for easy server-client communication."
authors = ["bub"]
license = "MIT"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@2"
Property = "bub/property@3"
Promise = "evaera/promise@4"
Janitor = "howmanysmall/janitor@1"
serializerUtil = "bub/serializerutil@1"
Sift = "csqrl/sift@0"